import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Homepage/Header";
import Footer from "./components/Homepage/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Applyqik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <main>
            <Header />

            {children}
            
            <Footer />
          </main>
        </body>
    </html>
  );
}
